import 'package:firebase_core/firebase_core.dart';

/// This file is normally generated by the FlutterFire CLI.
/// Replace the placeholder values with your Firebase project configuration
/// or regenerate using `flutterfire configure`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: 'YOUR_API_KEY',
      appId: 'YOUR_APP_ID',
      messagingSenderId: 'YOUR_SENDER_ID',
      projectId: 'clipus',
      storageBucket: 'clipus.appspot.com',
    );
  }
}